export const config = {
  recipientName: "My Love",
  senderName: "Your Love",
  profilePhoto: "/assets/images/profile.jpg",
  birthdayMessage:
    "On your special day, I hope every little moment brings you a reason to smile. Thank you for being exactly who you are and for making the world feel warmer just by being in it. Here’s to beautiful memories, brave new dreams, and a year filled with love.",
  gallery: [
    { src: "/assets/images/memory-1.jpg", caption: "A beautiful memory worth keeping forever." },
    { src: "/assets/images/memory-2.jpg", caption: "The kind of moment that always makes us smile." },
    { src: "/assets/images/memory-3.jpg", caption: "More adventures, laughter, and memories ahead." },
    { src: "/assets/images/memory-4.jpg", caption: "One of so many reasons today is worth celebrating." },
  ],
  playlist: [
  {
    title: "I Didn't Know What I Was Missing Until You",
    artist: "Until I Found You - Stephen Sanchez",
    cover: "/assets/images/cover-3.jpg",
    src: "/assets/music/song-1.mp3",
  },
  {
    title: "You're The Person I Always Want To Come Home To",
    artist: "Penjaga Hati - Nadhif Basalamah",
    cover: "/assets/images/cover-3.jpg",
    src: "/assets/music/song-2.mp3",
  },
  {
    title: "Wherever I Am, I Want It To Be With You",
    artist: "Here With Me - d4vd",
    cover: "/assets/images/cover-3.jpg",
    src: "/assets/music/song-3.mp3",
  },
  {
    title: "Happy Birthday To My Favorite Person",
    artist: "Lover - Taylor Swift",
    cover: "/assets/images/cover-3.jpg",
    src: "/assets/music/song-4.mp3",
  },
],
  backgroundMusic: "/assets/music/background.mp3",
  gameDuration: 20,
  gameSecretMessage: "So many hearts caught! Good thing mine was already yours.",
  ui: {
    pageTitle: "Birthday Surprise",
    pageDescription: "A heartfelt birthday surprise filled with memories, music, and wishes.",
    welcomeTitle: "A special surprise for you, {name}!",
    welcomeHint: "Tap the gift to open",
    openGiftLabel: "Open your birthday surprise",
    loading: "Preparing your surprise...",
    menuTitle: "For You!",
    menuSubtitle: "Made with love, from {sender}",
    back: "Back to menu",
    mute: "Mute background music",
    unmute: "Unmute background music",
    screens: {
      message: "Special Message",
      gallery: "Gallery",
      playlist: "Music Playlist",
      game: "Fun Challenge",
      wish: "Make a Wish",
    },
    birthdayGreeting: "Happy Birthday, {name}!",
    skip: "Skip",
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
    photoFallback: "Birthday memory",
    previousTrack: "Previous track",
    nextTrack: "Next track",
    play: "Play",
    pause: "Pause",
    trackFallback: "Album cover",
    gameTitle: "Catch the Hearts!",
    score: "Score",
    missed: "Missed",
    time: "Time",
    gameOver: "Time’s up!",
    finalScore: "You caught {score} hearts",
    secret: "WOW",
    playAgain: "Play Again",
    wishHint: "Tap every flame and make a wish",
    wishComplete: "May this year be as wonderful as you are, {name}!",
    relight: "Relight candles",
    candleLabel: "Blow out candle {number}",
  },
} as const;

export type Screen = "welcome" | "loading" | "menu" | "message" | "gallery" | "playlist" | "game" | "wish";

export const fill = (text: string, values: Record<string, string | number>) =>
  text.replace(/\{(\w+)\}/g, (match, key: string) => String(values[key] ?? match));